### ISSUE TITLE
 patch based method or segmention

### ISSUE THREAD

**Issue by XavierMFC** [jqyang22/CSIL#2]
thank you for you sharing.
I have a question that is this a patch-based classification method, rather segmentation?

**Comment by jqyang22** [comment]
> thank you for you sharing. I have a question that is this a patch-based classification method, rather segmentation?

Thank you for your interest in our work. The proposed method is a hyperspectral classification method based on patches, which can also be regarded as a pixel-by-pixel segmentation task in the field of computer vision.
