### ISSUE TITLE
Hello author, I encountered a problem while running your code. I would like to ask how to modify the training sample

### ISSUE THREAD

**Issue by chihuajiao** [jqyang22/CSIL#3]

**Comment by chihuajiao** [comment]
How should I set up my training samples to train based on percentages

**Comment by jqyang22** [comment]
> How should I set up my training samples to train based on percentages

Hi, you can modify the number of training pixels for each class by using the "generation_num" function in the class "product" of the func.py, and the remaining labeled pixels are the test samples. 
If you want to rewrite it to a percentage-based method, maybe you can refer to the “sampling” function in 3D_MSDNet_UP.py from the link:
https://github.com/leeguandong/Multi-Scale-Dense-Networks-for-Hyperspectral-Remote-Sensing-Image-Classification/blob/master/3D_MSDNet_UP.py

**Comment by chihuajiao** [comment]
thank you very much for your help
